theme: jekyll-theme-cayman



# --- General options --- #
title: [Flash-Aware Computing]
description: [Seoul National University,
              Computer ARchitecture & Embedded Systems Laboratory]

# Short description of your site

# --- Local development options ---
# If your website is hosted locally rather than on GitHub, then you need to uncomment the next two parameters to set the url and baseurl
# *** If you're not sure what this mean, then leave this section as it is. Only modify the url and baseurl if you know what you're doing!***

# url is the the website domain URL without a trailing slash
#url: "https://example.com"

# baseurl should be an empty string
#baseurl: ""
github:
  is_project_page: false
